 import type { Metadata } from "next";
import "../globals.css";
import { Toaster } from "sonner";
import localFont from "next/font/local";
import { IntProviders } from "./Intproviders";
import { Providers } from "@/providers";

const garamond = localFont({
  src: [
    {
      path: "../fonts/EBGaramond-ExtraBold.ttf",
      weight: "800",
      style: "normal"
    },
    {
      path: "../fonts/EBGaramond-Bold.ttf",
      weight: "700",
      style: "normal"
    },
     {
      path: "../fonts/EBGaramond-Medium.ttf",
      weight: "500",
      style: "normal"
    },
     {
      path: "../fonts/EBGaramond-Regular.ttf",
      weight: "400",
      style: "normal"
    },
   
  ],
   variable: '--font-garamond'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  }
}>) {
  return (
    
    <html lang="en">
      <body 
      
        className={`${garamond.className} ${garamond.variable} antialiased`}
      >
        <Providers>
        
        <Toaster richColors closeButton position="top-right"></Toaster>

        <IntProviders locale={params.locale}>       
          {children}

        </IntProviders>
  

        </Providers>
        
      </body>
    </html>
   
  );
}